### PR TITLE
Using AWSCredentialProvider for AWS plugins

### PR DESCRIPTION
**Pull request by timkral**
@john-brock @thespags 

Updating how plugins related to AWS (`filestore-s3`, `mapstore-dynamodb`, etc) are configured. It used to be that these required static access and secret key values in your `service.conf` file. I'm changing it to allow an `AWSCredentialsProvider` class name that is loaded dynamically at runtime. This gives much more flexibility in how AWS credentials are provided. For example:

- You can store credentials in a classpath file and use `ClasspathPropertiesFileCredentialsProvider` (this is what I do in the tests below)
- You can provide credentials via System properties and use `SystemPropertiesCredentialsProvider`
- You can provide credentials via Environment Variables and use `EnvironmentVariableCredentialsProvider`
- Or you can write your own `AwsCredentialsProvider` and use that

### CODE REVIEW

**Comment by thespags** [comment]
You should try writing tests for the other three scenarios or at least AwsCredentialsProvider. Well whatever you need to avoid losing .2% coverage.

Further for AwsCredentialsProvider, I'm wondering if you want to start an apps-builder-example repository. I'm wondering if we can think of some silly example, like swagger's Petstore, to create examples of your different providers.

**Comment by timkral** [comment]
I think the -0.2% is a side effect of how the test coverage numbers are calculated. This is basically just configuration code that's been condensed. So the 10 lines of configuration code (which were fully covered) are now 3 lines of configuration code (also fully covered). But from a code coverage perspective, I've dropped 7 covered lines of code which means my percentage goes down.

**Comment by thespags** [comment]
@timkral what about adding a story for the example repository?

**Comment by timkral** [comment]
Yes, that's a good idea.

**Comment by timkral** [comment]
@thespags I added a story for the example repository to the KanBan board.

**Pull request merged**
