### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thespags**
adding dependencies section for AppMock
and
configuration example

### CODE REVIEW

**Comment by thespags** [comment]
Do you want me to add this to the doc or save it for the wiki ?  @timkral

**Comment by timkral** [comment]
Let's save this for the wiki. Need to stop coding and do some work there.

**Comment by timkral** [comment]
I think we should feature freeze AppBuilder and only write doc and fix bugs that come up. What do you think?

**Comment by thespags** [comment]
Sounds reasonable. we will save this for the wiki.

**Pull request closed without merging**
